import { Breakdown, CrewMember, ShootDay } from "./types";

/** Every date computation here uses Date.UTC(...) explicitly and reads
 * back with getUTC*() — never the local-timezone Date constructor or
 * toISOString() — so a "YYYY-MM-DD" shoot date never silently shifts by
 * a day depending on the browser's timezone. */
function nextDayCompact(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  const next = new Date(Date.UTC(y, m - 1, d + 1));
  const yyyy = next.getUTCFullYear();
  const mm = String(next.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(next.getUTCDate()).padStart(2, "0");
  return `${yyyy}${mm}${dd}`;
}

/** Which cast members actually appear in this shoot day's scenes,
 * cross-referenced against the breakdown (not re-derived or guessed). */
export function castNamesForDay(day: ShootDay, breakdown: Breakdown): string[] {
  const sceneNumbers = new Set(day.scenes);
  const names = new Set<string>();
  for (const scene of breakdown.scenes) {
    if (sceneNumbers.has(scene.number)) {
      scene.characters.forEach((c) => names.add(c));
    }
  }
  return Array.from(names);
}

/** Builds a Google Calendar "quick add" link — no OAuth, no backend
 * call. Opening it in the filmmaker's own browser (already signed into
 * their Google account) pre-fills a real event; hitting Save sends real
 * invites to every guest, and RSVPs happen through Calendar itself. */
export function buildGoogleCalendarUrl(params: {
  projectName: string;
  day: ShootDay;
  breakdown: Breakdown;
  castEmails: Record<string, string>;
  crew: CrewMember[];
}): string | null {
  const { projectName, day, breakdown, castEmails, crew } = params;
  if (!day.date) return null;

  const castOnDay = castNamesForDay(day, breakdown);
  const guestEmails = Array.from(
    new Set([
      ...castOnDay.map((name) => castEmails[name]).filter(Boolean),
      ...crew.map((c) => c.email).filter(Boolean),
    ])
  );

  const startCompact = day.date.replace(/-/g, "");
  const endCompact = nextDayCompact(day.date);

  const hoursLine =
    day.cast_hours.length > 0
      ? `Hours needed: ${day.cast_hours.map((c) => `${c.name} ${c.hours_needed}h`).join(", ")}`
      : undefined;

  const detailsLines = [
    `Scenes: ${day.scenes.join(", ")}`,
    day.call_time_note,
    hoursLine,
    day.weather_flag,
    "",
    "Generated by VantageTime",
  ].filter((line) => line !== undefined && line !== null);

  const search = new URLSearchParams({
    action: "TEMPLATE",
    text: `${projectName} — Shoot Day ${day.day_number}`,
    dates: `${startCompact}/${endCompact}`,
    details: detailsLines.join("\n"),
    location: day.locations.join(", "),
  });
  if (guestEmails.length > 0) {
    search.set("add", guestEmails.join(","));
  }

  return `https://calendar.google.com/calendar/render?${search.toString()}`;
}
